services:
  - type: static
    name: posifeed-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_URL
        value: https://posifeed-api.onrender.com
    buildSettings:
      rootDir: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html